imports:
    - { resource: tables.yml }
services:
    sheer.knowledgebase.controller.index:
        class: sheer\knowledgebase\controller\index
        arguments:
            - '@config'
            - '@request'
            - '@pagination'
            - '@dbal.conn'
            - '@auth'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@sheer.knowledgebase.inc'
            - '%tables.articles_table%'
            - '%tables.categories_table%'

    sheer.knowledgebase.controller.category:
        class: sheer\knowledgebase\controller\category
        arguments:
            - '@config'
            - '@request'
            - '@pagination'
            - '@dbal.conn'
            - '@auth'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@sheer.knowledgebase.inc'
            - '%tables.articles_table%'
            - '%tables.categories_table%'

    sheer.knowledgebase.controller.article:
        class: sheer\knowledgebase\controller\article
        arguments:
            - '@config'
            - '@request'
            - '@dbal.conn'
            - '@auth'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@sheer.knowledgebase.inc'
            - '%tables.articles_table%'
            - '%tables.kb_attachments_table%'

    sheer.knowledgebase.controller.posting:
        class: sheer\knowledgebase\controller\posting
        arguments:
            - '@config'
            - '@request'
            - '@dbal.conn'
            - '@auth'
            - '@template'
            - '@user'
            - '@cache'
            - '@log'
            - '@?files.factory'
            - '@notification_manager'
            - '@plupload'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@controller.helper'
            - '@sheer.knowledgebase.inc'
            - '@sheer.knowledgebase.helper'
            - '%tables.logs_table%'
            - '%tables.categories_table%'
            - '%tables.articles_table%'
            - '%tables.kb_attachments_table%'

    sheer.knowledgebase.controller.library_search:
        class: sheer\knowledgebase\controller\library_search
        arguments:
            - '@config'
            - '@request'
            - '@dbal.conn'
            - '@auth'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@cache'
            - '@pagination'
            - '%core.root_path%'
            - '%core.php_ext% '
            - '@sheer.knowledgebase.inc'
            - '%tables.articles_table%'

    sheer.knowledgebase.controller.approve:
        class: sheer\knowledgebase\controller\approve
        arguments:
            - '@config'
            - '@request'
            - '@dbal.conn'
            - '@auth'
            - '@template'
            - '@user'
            - '@cache'
            - '@log'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@sheer.knowledgebase.inc'
            - '@sheer.knowledgebase.helper'
            - '%tables.articles_table%'

    sheer.knowledgebase.listener:
        class: sheer\knowledgebase\event\listener
        arguments:
            - '@template'
            - '@controller.helper'
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '%core.root_path%'
            - '%tables.kb_attachments_table%'
        tags:
            - { name: event.listener }

    sheer.knowledgebase.inc:
        class: sheer\knowledgebase\inc\functions_kb
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@cache'
            - '@user'
            - '@template'
            - '@auth'
            - '@log'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.kb_config_table%'
            - '%tables.articles_table%'
            - '%tables.categories_table%'
            - '%tables.kb_options_table%'
            - '%tables.kb_groups_table%'
            - '%tables.kb_users_table%'
            - '%tables.logs_table%'
            - '%tables.kb_attachments_table%'

    sheer.knowledgebase.helper:
        class: sheer\knowledgebase\core\helper
        arguments:
            - '@dbal.conn'
            - '@notification_manager'

    sheer.knowledgebase.notification.type.need_approval:
        class: sheer\knowledgebase\notification\need_approval
        scope: prototype # scope MUST be prototype for this to work!
        parent: notification.type.base
        calls:
            - [set_user_loader, [@user_loader]]
        tags:
            - { name: notification.type }

    sheer.knowledgebase.notification.type.approve:
        class: sheer\knowledgebase\notification\approve
        scope: prototype # scope MUST be prototype for this to work!
        parent: notification.type.base
        calls:
            - [set_user_loader, [@user_loader]]
        tags:
            - { name: notification.type }

    sheer.knowledgebase.notification.type.disapprove:
        class: sheer\knowledgebase\notification\disapprove
        scope: prototype # scope MUST be prototype for this to work!
        parent: notification.type.base
        calls:
            - [set_user_loader, [@user_loader]]
        tags:
            - { name: notification.type }

    sheer.knowledgebase.controller.kb_file:
        class: sheer\knowledgebase\controller\kb_file
        arguments:
            - '@user'
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@sheer.knowledgebase.inc'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.kb_attachments_table%'

    sheer.knowledgebase.admin.controller:
        class: sheer\knowledgebase\controller\admin_controller
        arguments:
            - '@user'
            - '@cache'
            - '@config'
            - '@dbal.conn'
            - '@template'
            - '@request'
            - '@pagination'
            - '@controller.helper'
            - '%core.root_path%'
            - '@sheer.knowledgebase.inc'
            - '%tables.kb_attachments_table%'
            - '%tables.articles_table%'

    sheer.knowledgebase.controller.set_order:
        class: sheer\knowledgebase\controller\set_order
        arguments:
            - '@dbal.conn'
            - '@request'
            - '@sheer.knowledgebase.inc'
            - '%tables.articles_table%'
